### ISSUE TITLE
package-list query leads to denied access for newer packages

### ISSUE THREAD

**Issue by raphw** [maxcellent/javadoc.io#100]
Thanks for hosting javadoc.io.

It seems like newer versions of packages do no longer offer access to the package-list folder. Comparing the two versions:

```cmd
curl https://www.javadoc.io/doc/com.google.guava/guava/27.1-jre/package-list
curl https://www.javadoc.io/doc/com.google.guava/guava/31.1-jre/package-list
```

The call works for version 27 but not for the latest release 31. As a consequence, those dependencies cannot be linked from the javadoc tool via the *link* option.

This seems to have been fixed in #74 but does no longer work.

**Comment by Marcono1234** [comment]
This might be a Guava specific issue, see https://github.com/google/guava/issues/5653, or in general affect all projects which create their Javadoc with a newer `javadoc` version, which uses `element-list` instead of `package-list`.
If you inspect the Guava `-javadoc.jar` files from Maven Central, you will see that the latest Guava JARs only include an `element-list` file.

**Comment by raphw** [comment]
Of course. I was confused by the response code I got. I solved this differently.
