### ISSUE TITLE
Wrong link generated for cross-module dependency

### ISSUE THREAD

**Issue by hakanai** [maxcellent/javadoc.io#67]
Just discovered this site today, really nice. :)

I found some broken links though.

Example here:

https://javadoc.io/doc/com.google.errorprone/error_prone_core/latest/com/google/errorprone/bugpatterns/UnnecessaryMethodInvocationMatcher.html

The "implements BugChecker.MethodInvocationTreeMatcher" hyperlink points to here:

http://nexus.sonatype.org/oss-repository-hosting.html/error_prone_parent/error_prone_check_api/apidocs/com/google/errorprone/bugpatterns/BugChecker.MethodInvocationTreeMatcher.html?is-external=true

Whereas it seems the correct URL would have been:

https://javadoc.io/doc/com.google.errorprone/error_prone_check_api/latest/com/google/errorprone/bugpatterns/UnnecessaryMethodInvocationMatcher.html

**Comment by maxcellent** [comment]
hmmm I actually downloaded https://repo1.maven.org/maven2/com/google/errorprone/error_prone_check_api/2.5.1/error_prone_check_api-2.5.1-javadoc.jar  but cannot find `MethodInvocationTreeMatcher`. 

You would need to contact library owner to move the class to api module.

Closing the ticket now as this is considered expected behavior.
