### ISSUE TITLE
Search bar incorrectly adds `/undefined` path to URL

### ISSUE THREAD

**Issue by mialbu** [maxcellent/javadoc.io#95]
The search seems to have a problem when trying to search for docs of the `neow3j` library. It incorrectly adds an `/undefined` path to the URL. When removing it, the docs are accessible just fine. Might be related to #27.

![image](https://user-images.githubusercontent.com/53603111/172355459-4c753901-e65d-4fb8-8d1b-30d25d027111.png)

![image](https://user-images.githubusercontent.com/53603111/172355495-66a845c8-af9d-4cd3-b668-d00d15a5eefc.png)

**Comment by maxcellent** [comment]
This looks like an issue of JDK itself. You can reproduce by downloading .jar file from maven central directly: https://repo1.maven.org/maven2/io/neow3j/contract/3.17.1/

https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url

**Comment by Marcono1234** [comment]
@maxcellent, even though this is a JDK bug, do you think it would be feasible if javadoc.io could detect when such an incorrect URL is created and redirect to the proper page (or maybe in general just redirect `.../<version>/undefined` to `.../<version>` if the current URL leads to 404)? The issue is that even if projects fixed this by upgrading to a newer JDK version, the previously published Javadoc would still remain broken and cannot be fixed by the project maintainers.

Though no worries if you think this is not worth it.
